### PR TITLE
Fix warnings2

### PR DESCRIPTION
**Pull request by StefanBruens**
Add prototypes for the lex autogenerated functions, catches prototype mismatches

### CODE REVIEW

**Comment by rubund** [comment]
The problem is that we do not have any good test suite setup for graywolf. Therefore these big refactoring changes are very dangerous. This is not the first time there have been problems with these pull requests. Since Tim caught several void / int errors, and none of us have spent the time to go through all the changes, we do not know if there are more of the same type of errors in your pull request. Please make sure you test your changes properly on several designs before and after when making such pull requests. (since we do not have an automatic test suite).

I do actually prefer to only accept pull requests that are handcrafted to fix "real" single bugs. But since this time, your pull request looked quite well organised, I made an exception. But I reverted the whole merge as soon as problems with it were reported.

If I were familar with the code of graywolf, things would have been much easier for me to review. I still have not had time to dive into the code. My job has consisted only of modernising the build setup (it was nearly impossible to build before), and accept bug fixes and improvements reported by Tim.

Cheers.

**Comment by StefanBruens** [comment]
If you look at e.g. https://github.com/rubund/graywolf/issues/21, this is one of the places where the compiler very likely gives a warning you are truncating a value. Unfortunately this is almost impossible to spot because there are just to many warnings thrown.

There are plenty of warnings still, e.g. about bad casts from pointer (64 bit on 64bit archs) to int (32 bit on Linux, typically). These are actual bugs.

Regarding test suites, a very good first step would be to add designs which have shown to be problematic. If Tim has failing designs, please ask him if he is willing to share.

**Comment by rubund** [comment]
It has been merged into the new "dev" branch. See the new section about "Contributions" in the README.md file.

Thank you @StefanBruens

**Comment by rubund** [comment]
@StefanBruens:  Your changes are not on the "master" branch! I found a few "bugs" which were introduced by your pull request, but they are fixed now (mainly "void" added to functions which actually returned values).

I have also gotten rid of all other warnings except "implicit-function-declaration", which I have temporarily disabled. This now has resulted in a completely clean build log!

> Regarding test suites, a very good first step would be to add designs which have shown to be problematic. If Tim has failing designs, please ask him if he is willing to share.

I have established a test suite, so we at least get a sanity check whenever changes/ refactoring is done. Instructions for using the test suite are in the main README file.

Thanks for your effort!

Cheers

**Pull request closed without merging**
