### PR TITLE
Cmake fixes

### PR DESCRIPTION
**Pull request by StefanBruens**

### CODE REVIEW

**Comment by StefanBruens** [comment]
The second patch fixes #18

**Comment by rubund** [comment]
Fails with
`CMake Error at src/Ylib/CMakeLists.txt:15 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "ycadgraywolf".`

when trying to build as before. I have not checked why.

**Comment by StefanBruens** [comment]
@rubund - can you try again?

**Comment by rubund** [comment]
Merged to "dev" branch

**Comment by StefanBruens** [comment]
Sorry, but thats plain wrong ...
Please read https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

**Comment by rubund** [comment]
No no, it is correct, but from the page you've linked to, it sounds like a slightly shorter version would be to replace ${CMAKE_INSTALL_LIBDIR} with ${CMAKE_INSTALL_FULL_LIBDIR} these places. I can try that tonight. Thanks

Cheers,
Ruben

**Comment by rubund** [comment]
Don't misunderstand! I am talking about places such as:

1:
https://github.com/rubund/graywolf/blob/master/config.h.in

2:

```
install(CODE "EXECUTE_PROCESS(COMMAND ln -sf flow.noroute flow WORKING_DIRECTORY ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/graywolf/bin/flow)")
```

3:
```
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
```

and so on.

**Not in the install instructions for build targets** (when the _DESTINATION_ keyword is used) :)

**Comment by StefanBruens** [comment]
This break systems where CMAKE_INSTALL_PREFIX is set and CMAKE_INSTALL_LIBDIR is an absolute path - you end up with e.g. /usr/usr/lib
This is the case for Fedora/RHEL, openSUSE/SLE, Gentoo, ...
CMAKE_INSTALL_FULL_<dir> is the correct variable to use in the cases above, as it handles absolute pathes correctly.

**Comment by rubund** [comment]
> This is the case for Fedora/RHEL, openSUSE/SLE, Gentoo, ...

Strange that I do not see this behaviour in CentOS (which is supposed to be a RHEL clone more or less) nor Debian. Also Tim got some problems on his computer before I fixed the RPATH issue (and he is using Fedora and CentOS - not sure exactly which of the two he tried it on).

But I agree that changing to CMAKE_INSTALL_FULL_..  is more future proof.

Can you test this simple CMakeLists.txt on your computer:
```
cmake_minimum_required (VERSION 3.4)

include(GNUInstallDirs)

MESSAGE("CMAKE_INSTALL_LIBDIR is ${CMAKE_INSTALL_LIBDIR} on my computer")
MESSAGE("CMAKE_INSTALL_FULL_LIBDIR is ${CMAKE_INSTALL_FULL_LIBDIR} on my computer")
```
?

**Comment by StefanBruens** [comment]
This happens in the automated build environments, e.g. Koji (RH/Fedora), OBS (SUSE/openSUSE), where CMAKE_INSTALL_PREFIX and CMAKE_INSTALL_LIBDIR are explicitly set, not when you do a local build/installation.

**Pull request closed without merging**
